version: '3'
services:
  
  postgresql:
    image: postgres:13
    restart: unless-stopped
    container_name: postgres-container
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=common_app
      - TZ=America/Sao_Paulo
      - PGTZ=America/Sao_Paulo
    volumes:
      - ./.volumes/database:/var/lib/postgresql/data

  api:
    image: maven:3.8.3
    restart: unless-stopped
    container_name: api-container
    links:
      - postgresql
    depends_on:
      - postgresql
    ports:
      - "8080:8080"
      - "8000:8000"
    environment:
      DB_URL: "postgresql:5432/common_app"
      DB_USERNAME: "root"
      DB_PASSWORD: "root"
    volumes:
      - ./:/app
      - ./.volumes/maven:/root/.m2
    working_dir: /app
    command: mvn spring-boot:run